FROM apache/airflow:2.9.2

USER root
RUN apt-get update && \
    apt-get install -y --no-install-recommends openjdk-17-jdk procps && \
    rm -rf /var/lib/apt/lists/*

ENV JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64

USER airflow
RUN pip install --no-cache-dir "setuptools<67.0.0" && \
    pip install --no-cache-dir \
    pyspark==3.5.3 \
    boto3==1.34.0 \
    psycopg2-binary==2.9.9 \
    pandas==2.1.4
